before:
  hooks:
  - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    binary: bin/{{ .ProjectName }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha512

archive:
  format: tar.gz
  files:
  - LICENSE
  - README.md

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
